# SonarQube Project Configuration
sonar.projectKey=network-telemetry-engine
sonar.projectName=Network Telemetry and Slice Quality Engine
sonar.projectVersion=1.0.0

# Source & Test paths
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

# Test Coverage report path
sonar.python.coverage.reportPaths=coverage.xml

# Server connection
sonar.host.url=http://localhost:9000
sonar.login=squ_90bec4ea67defe149a4bf818f1903a12c5c05f14

